_target_: src.models.modelmodule.BaseModelModule

defaults:
  - model: cdcn
  - metrics_params: multiclass

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: ${lr}

project: ${project}
experiment: ${experiment}
seed: ${seed}
save_outputs: ${save_outputs}
pretrain_epochs: ${pretrain_epochs}

cfg_dict:
  model: cdcn
  lr: ${lr}
  batch_size: ${batch_size}
  epochs: ${epochs}
  segment_length: ${segment_length}
  std: ${std}
  min_crop_size: ${min_crop_size}
  augmentations: ${augmentation}
  experiment_hparams:
   - cdcn
   - ${lr}
   - ${batch_size}
   - ${mode}
   - ${std}
    - ${min_crop_size}
