_target_: src.data.data_splits.train_test_split_proposed
_partial_: True
sampler:
  _target_: src.data.data_splits.CombinationSampler
  list1:
    - ['K001']
    - ['K002']
    - ['K003']
    - ['K004']
    - ['K005']
    - ['K006']
  list2:
    - ['KA01']
    - ['KA03']
    - ['KA05']
    - ['KA06']
    - ['KA07']
    - ['KA08']
    - ['KA09']
  list3:
    - ['KI01']
    - ['KI03']
    - ['KI05']
    - ['KI07']
    - ['KI08']
  random_seed: 42
run: ${random_state}
healthy_bearing_ids: ['K001', 'K002', 'K003', 'K004', 'K005', 'K006']
outer_bearing_ids: ['KA01', 'KA03', 'KA05', 'KA06', 'KA07', 'KA08', 'KA09']
inner_bearing_ids: ['KI01', 'KI03', 'KI05', 'KI07', 'KI08']
