_target_: src.data.data_splits.train_test_split_proposed
_partial_: True
sampler:
  _target_: src.data.data_splits.CombinationSampler
  list1:
    - ['K001']
    - ['K002']
    - ['K003']
    - ['K004']
    - ['K005']
    - ['K006']
  list2:
    - ['KA04']
    - ['KA15']
    - ['KA16']
    - ['KA22']
    - ['KA30']
  list3:
    - ['KI04']
    - ['KI14']
    - ['KI16']
    - ['KI18']
    - ['KI21']
    - ['KI17']
  random_seed: 42
run: ${random_state}
healthy_bearing_ids: ['K001', 'K002', 'K003', 'K004', 'K005', 'K006']
outer_bearing_ids: ['KA04', 'KA15', 'KA16', 'KA22', 'KA30']
inner_bearing_ids: ['KI04', 'KI14', 'KI16', 'KI18', 'KI21', 'KI17']
