_target_: sklearn.pipeline.Pipeline
steps:
- - raw_psd
  - _target_: src.data.feature_engineering.transforms.create_transform
    metrics: []
    representation:
      name: psd_raw
      func:
        _target_: feature_extraction.signal_representations.psd.psd_transform
        _partial_: true
      params:
        signal_column: vibration
        sampling_rate_column: fs
        cutoff: null
