_target_: src.data.pydantic_models.BearingDataset

defaults:
  - split_function: null


name: Synthetic
add_signal_function:
  _target_: src.utils.add_signal_data.add_signal_to_synthetic_dataset
  _partial_: True
signal_column: signal
label_column:
  - label
